"""Core :class:`~sqlalchemy.Table` handles for the retrieval adapter (SDD A.8.2).

This module deliberately defines **no schema**. Ticket #6 made
``app/infrastructure/persistence/models.py`` the single declarative source of
truth -- ``migrations/env.py`` diffs ``Base.metadata`` and
``tests/integration/test_orm_models.py`` fails if the models and the migrations
drift. A second ``MetaData()`` here would be a second source of truth, invisible
to that guard, and the first schema change made in one place and not the other
would produce a silently wrong autogenerated migration.

So these are re-exports of the mapped tables, not declarations:

* The retrieval store issues set-based SQL -- vector distance ordering,
  ``ts_rank``, ``ON CONFLICT`` upserts -- and maps rows straight to frozen port
  DTOs. An identity map and unit of work would buy it nothing, so it works
  against ``Table`` objects rather than ORM entities.
* ``Model.__table__`` gives exactly that, while keeping one definition. The
  column collection is keyed by real column name, so ``chunks.c.metadata``
  resolves even though the declarative attribute has to be called ``metadata_``
  (``metadata`` being reserved on ``DeclarativeBase``).

Schema changes belong in ``models.py`` plus an Alembic revision, never here.
"""

from __future__ import annotations

from typing import cast

import sqlalchemy as sa

from app.infrastructure.persistence.models import (
    EMBEDDING_DIMENSIONS,
    ChunkEmbeddingModel,
    ChunkModel,
    DocumentModel,
)

#: Dimensionality of the configured embedding model (``all-MiniLM-L6-v2``).
#: Re-exported from the models so there is one constant, not two that can
#: disagree. Must equal ``settings.embedding.dimensions`` and the ``VECTOR(n)``
#: column; the adapter validates every incoming vector against the value it was
#: constructed with, so a mismatch fails before reaching PostgreSQL.
EMBEDDING_DIM = EMBEDDING_DIMENSIONS

#: Name of the uniqueness constraint that makes embedding upserts idempotent.
#: Referenced explicitly by ``ON CONFLICT ON CONSTRAINT``, so it is shared here
#: rather than duplicated as a string literal in the adapter. Declared on
#: :class:`~app.infrastructure.persistence.models.ChunkEmbeddingModel`.
CHUNK_EMBEDDING_PROVENANCE_CONSTRAINT = "uq_chunk_embedding_provenance"

#: ``DeclarativeBase.__table__`` is typed as the broader ``FromClause`` because a
#: mapped class may in principle map to any selectable. These three map to real
#: tables, and the adapter needs the narrower type -- ``insert()`` accepts a
#: ``TableClause``, not a ``FromClause`` -- so the cast states what is already
#: true rather than widening anything.
documents = cast(sa.Table, DocumentModel.__table__)
chunks = cast(sa.Table, ChunkModel.__table__)
chunk_embeddings = cast(sa.Table, ChunkEmbeddingModel.__table__)

__all__ = [
    "CHUNK_EMBEDDING_PROVENANCE_CONSTRAINT",
    "EMBEDDING_DIM",
    "chunk_embeddings",
    "chunks",
    "documents",
]
