#!/usr/bin/env python
"""install-hooks — Install the pre-commit quality gate hook into .git/hooks.

Usage:
    python scripts/install-hooks.py

Copies scripts/pre-commit-check.py as .git/hooks/pre-commit so that every
`git commit` automatically runs lint, type-check, architecture contracts,
and tests before allowing the commit through.
"""

from __future__ import annotations

import os
import stat
import sys
from pathlib import Path


def main() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    hooks_dir = repo_root / ".git" / "hooks"
    source = repo_root / "scripts" / "pre-commit-check.py"
    target = hooks_dir / "pre-commit"

    if not hooks_dir.is_dir():
        print(f"Error: {hooks_dir} does not exist. Are you in a git repo?")
        return 1

    if not source.is_file():
        print(f"Error: {source} not found.")
        return 1

    # Write a shell wrapper that invokes the Python script
    wrapper = f"""#!/bin/sh
# Auto-generated by install-hooks.py — do not edit manually.
python "{source}" "$@"
"""
    target.write_text(wrapper, encoding="utf-8")
    # Make executable
    st = os.stat(target)
    os.chmod(target, st.st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)

    print(f"✅ Pre-commit hook installed at {target}")
    print("   Every `git commit` will now run quality checks automatically.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
